Payum/Payum

UPGRADE.md, src/Payum/Core/Bridge/Doctrine/Storage/DoctrineStorage.php, src/Payum/Core/Bridge/Zend/Storage/TableGatewayStorage.php, src/Payum/Core/Storage/FilesystemStorage.php, src/Payum/Core/Storage/StorageInterface.php, src/Payum/Core/Tests/Bridge/Doctrine/Storage/DoctrineStorageTest.php, src/Payum/Core/Tests/Bridge/Zend/Storage/TableGatewayStorageTest.php, src/Payum/Core/Tests/Storage/FilesystemStorageTest.php
=> [storage] Add `StorageInterface::findBy`

src/Payum/Offline/Resources/docs/get-it-started.md
Hello, this is just a small typo fix in the Offline component docs.
=> Fix typo in offline docs

src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/CancelRecurringPaymentsProfileAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/PaymentFactory.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/Api/CancelRecurringPaymentsProfileActionTest.php
* Use generic Cancel request class
* Reuse manageRecurringPaymentsProfileStatus code
* Add unit tests
=> * Add skeleton code for canceling recurring payments

UPGRADE.md, src/Payum/Core/Model/Order.php, src/Payum/Core/Model/OrderInterface.php, src/Payum/Core/Tests/Model/OrderTest.php
Fixes https://github.com/Payum/Payum/issues/206
=> [order] add setter and getter for credit card on order.

UPGRADE.md, src/Payum/AuthorizeNet/Aim/Action/ConvertOrderAction.php, src/Payum/Core/Gateway.php, src/Payum/Core/GatewayAwareInterface.php, src/Payum/Core/GatewayFactory.php, src/Payum/Core/GatewayFactoryInterface.php, src/Payum/Core/GatewayInterface.php, src/Payum/Core/Model/GatewayConfig.php, src/Payum/Core/Model/GatewayConfigInterface.php, src/Payum/Core/Model/Order.php, src/Payum/Core/Model/OrderInterface.php, src/Payum/Core/Model/Payment.php, src/Payum/Core/Model/PaymentInterface.php, src/Payum/Core/Payment.php, src/Payum/Core/PaymentAwareInterface.php, src/Payum/Core/PaymentFactory.php, src/Payum/Core/Registry/GatewayFactoryRegistryInterface.php, src/Payum/Core/Registry/GatewayRegistryInterface.php, src/Payum/Core/Registry/PaymentFactoryRegistryInterface.php, src/Payum/Core/Registry/PaymentRegistryInterface.php, src/Payum/Core/Request/Convert.php, src/Payum/Stripe/Action/Api/CreateCustomerAction.php, src/Payum/Stripe/Request/Api/CreateCustomer.php
https://github.com/Payum/Payum/issues/335
=> [payum] introduce Gateway interfaces and classes. Deprecate payment ones.

composer.json, src/Payum/Core/Bridge/Symfony/Validator/Constraints/CreditCardDate.php, src/Payum/Core/Bridge/Symfony/Validator/Constraints/CreditCardDateValidator.php, src/Payum/Core/Tests/Bridge/Symfony/Validator/Constraints/CreditCardDateValidatorTest.php
=> Move Validator from PayumBundle

src/Payum/Core/Bridge/Symfony/Validator/Constraints/CreditCardDateValidator.php
To be compatible with symfony < 2.5
=> Test if method buildViolation exist and fallback to addViolation 

src/Payum/Stripe/Resources/views/Action/obtain_checkout_token.html.twig, src/Payum/Stripe/Tests/Functional/Resources/Views/ObtainTokenTemplateTest.php
This is my first contribution to payum and I couldn't find any contribution guidelines so let me know if there's any styling issues or extra tests etc I need to add.
=> Added currency to checkout token template

src/Payum/AuthorizeNet/Aim/Action/CaptureAction.php, src/Payum/AuthorizeNet/Aim/Tests/Action/CaptureActionTest.php, src/Payum/AuthorizeNet/Aim/Tests/Action/ConvertPaymentActionTest.php, src/Payum/Be2Bill/Action/CaptureAction.php, src/Payum/Be2Bill/Tests/Action/CaptureActionTest.php, src/Payum/Be2Bill/Tests/Action/ConvertPaymentActionTest.php, src/Payum/Core/Bridge/Symfony/Action/ObtainCreditCardAction.php, src/Payum/Core/Request/ObtainCreditCard.php, src/Payum/Core/Tests/Action/CapturePaymentActionTest.php, src/Payum/Core/Tests/BaseConvertPaymentActionTest.php, src/Payum/Core/Tests/Bridge/Symfony/Action/ObtainCreditCardActionTest.php, src/Payum/Core/Tests/Model/CreditCardTest.php, src/Payum/Core/Tests/Model/PaymentTest.php, src/Payum/Core/Tests/Request/ObtainCreditCardTest.php, src/Payum/Offline/Tests/Action/ConvertPaymentActionTest.php, src/Payum/Payex/Tests/Action/ConvertPaymentActionTest.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/ConvertPaymentActionTest.php, src/Payum/Paypal/ProCheckout/Nvp/Action/CaptureAction.php, src/Payum/Paypal/ProCheckout/Nvp/Tests/Action/CaptureActionTest.php, src/Payum/Paypal/ProCheckout/Nvp/Tests/Action/ConvertPaymentActionTest.php, src/Payum/Stripe/Tests/Action/ConvertPaymentActionTest.php
Fixes https://github.com/Payum/Payum/issues/397
=> Pass model with obtain credit card request

src/Payum/Paypal/ExpressCheckout/Nvp/Action/ConvertPaymentAction.php
Paypal does not show description
=> Fix empty paypal description

src/Payum/Be2Bill/Action/NotifyAction.php, src/Payum/Be2Bill/Action/NotifyPaymentAction.php, src/Payum/Be2Bill/Be2BillOffsiteGatewayFactory.php, src/Payum/Be2Bill/Resources/docs/index.md, src/Payum/Be2Bill/Resources/docs/notifications.md, src/Payum/Be2Bill/Tests/Action/CaptureActionTest.php, src/Payum/Be2Bill/Tests/Action/CaptureOffsiteActionTest.php, src/Payum/Be2Bill/Tests/Action/ConvertPaymentActionTest.php, src/Payum/Be2Bill/Tests/Action/NotifyActionTest.php, src/Payum/Be2Bill/Tests/Action/NotifyPaymentActionTest.php, src/Payum/Be2Bill/Tests/Action/StatusActionTest.php, src/Payum/Be2Bill/Tests/Be2BillDirectPaymentFactoryTest.php, src/Payum/Be2Bill/Tests/Be2BillOffsiteGatewayFactoryTest.php, src/Payum/Be2Bill/Tests/bootstrap.php, src/Payum/Core/Tests/GenericActionTest.php
=> [be2bill] Implement basic notify action.

src/Payum/Core/Exception/RequestNotSupportedException.php, src/Payum/Core/Resources/docs/troubleshooting.md, src/Payum/Core/Tests/Exception/RequestNotSupportedExceptionTest.php
fixes https://github.com/Payum/Payum/issues/424
=> [exception] add suggestion on how to troubleshoot request not supported issues.

src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/DoCaptureAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Action/AuthorizeAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Action/CaptureAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Action/PurchaseAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Api.php, src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php, src/Payum/Paypal/ExpressCheckout/Nvp/Request/Api/DoCapture.php, src/Payum/Paypal/ExpressCheckout/Nvp/Resources/docs/authorize-order.md, src/Payum/Paypal/ExpressCheckout/Nvp/Resources/docs/index.md, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/Api/DoCaptureActionTest.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/AutorizeActionTest.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Request/Api/DoCaptureTest.php
ping @toooni addition to https://github.com/Payum/Payum/pull/429
TODO: 
* tests
* doc
=> [paypal][ec] add support of authorize operation

src/Payum/Klarna/Checkout/Action/Api/BaseApiAwareAction.php, src/Payum/Klarna/Checkout/Action/Api/CreateOrderAction.php, src/Payum/Klarna/Checkout/Action/Api/FetchOrderAction.php, src/Payum/Klarna/Checkout/Action/Api/UpdateOrderAction.php, src/Payum/Klarna/Checkout/Tests/Action/Api/CreateOrderActionTest.php, src/Payum/Klarna/Checkout/Tests/Action/Api/FetchOrderActionTest.php, src/Payum/Klarna/Checkout/Tests/Action/Api/UpdateOrderActionTest.php
Subtask of https://github.com/Payum/Payum/issues/435
=> [klarna] Add timeout tolerant fetch\create\update order.

src/Payum/Core/PayumBuilder.php, src/Payum/Core/Tests/PayumBuilderTest.php, src/Payum/Skeleton/README.md
fixes https://github.com/Payum/Payum/issues/452
=> [builder] Add abiliry to pass gateway factory factory, as callable

UPGRADE.md, composer.json, src/Payum/Stripe/Action/Api/CreateChargeAction.php, src/Payum/Stripe/Action/Api/CreateCustomerAction.php, src/Payum/Stripe/StripeCheckoutGatewayFactory.php, src/Payum/Stripe/composer.json
=> Updates stripe api to 3.6

src/Payum/Paypal/ExpressCheckout/Nvp/Action/PaymentDetailsStatusAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/PaymentDetailsStatusActionTest.php
=> Fixed paypal status does not detect cancelled payments

src/Payum/Core/Bridge/Symfony/ContainerAwareCoreGatewayFactory.php, src/Payum/Core/Bridge/Twig/TwigUtil.php, src/Payum/Core/CoreGatewayFactory.php, src/Payum/Core/Tests/Bridge/Symfony/ContainerAwareCoreGatewayFactoryTest.php, src/Payum/Core/Tests/CoreGatewayFactoryTest.php
~~**TODO** There is a problem, The loader is added each time gateways are created. Not good. I have to find a way to fix it.~~
=> [twig] register payums template loader with required paths

src/Payum/Core/Bridge/Symfony/Action/GetHttpRequestAction.php, src/Payum/Core/Bridge/Symfony/Action/ObtainCreditCardAction.php
Fixes https://github.com/Payum/PayumBundle/issues/346
=> Allow Symfony 3 request stack

src/Payum/Core/Resources/docs/instant-payment-notification.md, src/Payum/Core/Resources/docs/scripts/refund-script.md
Fixed class name in refund example
=> [DOC] small doc fixes

src/Payum/Core/Resources/docs/supported-gateways.md
Including custom OTP Hungary gateway.
=> Support for payments with OTP Hungary

src/Payum/Core/Resources/docs/how-to-contribute-from-subrepository.md, src/Payum/Core/Resources/docs/index.md
fixes https://github.com/Payum/Payum/issues/524
=> [doc] how to contribute from sub repository.

src/Payum/Core/Model/GatewayConfigInterface.php, src/Payum/Core/PayumBuilder.php, src/Payum/Core/Registry/AbstractRegistry.php, src/Payum/Core/Registry/DynamicRegistry.php, src/Payum/Core/Registry/GatewayRegistryInterface.php, src/Payum/Core/Registry/SimpleRegistry.php, src/Payum/Core/Tests/Registry/DynamicRegistryTest.php
fixes https://github.com/Payum/Payum/issues/532, https://github.com/Payum/Payum/issues/539, https://github.com/Payum/Payum/issues/531
=> [registry] Improve DynamicRegistry

composer.json, src/Payum/Core/CoreGatewayFactory.php, src/Payum/Core/Tests/CoreGatewayFactoryTest.php
- Fixed default client creation issue for CurlAdapter;
- Added httplug.stream_factory to default options
=> Fixed default client creation issue for CurlAdapter

.travis.yml, src/Payum/Core/PayumBuilder.php, src/Payum/Core/Resources/docs/scripts/index.md, src/Payum/Core/Tests/PayumBuilderTest.php, src/Payum/Paypal/Masspay/Nvp/Resources/docs/get-it-started.md
- add default storage for payout model
- add a payout path to generic token factory
- fix typos in the docs.
fixes https://github.com/Payum/Payum/issues/548
=> [paypal][masspay] Fix bugs.

src/Payum/Paypal/ExpressCheckout/Nvp/Resources/docs/recurring-payments-basics.md
Added a few more comments to help people understand the set up and avoid some pitfalls.
=> Added some fixes, changed some of the english

src/Payum/Core/Security/GenericTokenFactory.php, src/Payum/Core/Security/GenericTokenFactoryInterface.php, src/Payum/Core/Tests/Security/GenericTokenFactoryTest.php
- deprecate GenericTokenFactoryInterface.
- prepare ground for https://github.com/Payum/Payum/pull/579
=> [security] Add createCancelToken method

src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/DoVoidAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Action/PaymentDetailsStatusAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Api.php, src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php, src/Payum/Paypal/ExpressCheckout/Nvp/Request/Api/DoVoid.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/Api/DoVoidActionTest.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/CancelActionTest.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/PaymentDetailsStatusActionTest.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Request/Api/DoVoidTest.php
extends https://github.com/Payum/Payum/pull/579/files with some code cleanups and fixes
=> Paypal do void

src/Payum/Stripe/Action/GetCreditCardTokenAction.php, src/Payum/Stripe/Resources/docs/store-card-and-use-later.md, src/Payum/Stripe/StripeCheckoutGatewayFactory.php, src/Payum/Stripe/Tests/Action/GetCreditCardTokenActionTest.php
fixes https://github.com/Payum/Payum/issues/572
=> [stripe] add an action to get a credit card token from payment details.

src/Payum/Stripe/Action/StatusAction.php, src/Payum/Stripe/Tests/Action/StatusActionTest.php
fixes https://github.com/Payum/Payum/issues/556
=> [stripe] error not detected in some cases.

README.md
Just noticed a small typo in Readme.md. Here is the PR :)
=> Small typo-fix in Readme.md

src/Payum/Paypal/ExpressCheckout/Nvp/Action/PaymentDetailsStatusAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/PaymentDetailsStatusActionTest.php
Fail reversed payments (chargebacks)
Discussion in #609
=> Mark reversed payments failed

composer.json
Updated composer.json, fixes https://github.com/Payum/Payum/issues/616.
=> Twig 2.x - compatibility

src/Payum/Paypal/Rest/Tests/sdk_config.ini
=> Fix comments starting with # are deprecated

docs/index.md, docs/sofort/disable-notifications.md, src/Payum/Sofort/Api.php, src/Payum/Sofort/SofortGatewayFactory.php, src/Payum/Sofort/Tests/SofortGatewayFactoryTest.php, src/Payum/Sofort/Tests/bootstrap.php, src/Payum/Sofort/phpunit.xml.dist
fixes https://github.com/Payum/Payum/issues/628
=> [sofort] Add ability to disable notifications.

composer.json, src/Payum/AuthorizeNet/Aim/composer.json, src/Payum/Klarna/Checkout/composer.json, src/Payum/Stripe/composer.json
* Authorize.NET AIM 1.8 or higher
* Stripe API 3.x and 4.x
* Klarna Checkout API 1.x and 2.x
fixes https://github.com/Payum/Payum/issues/630, https://github.com/Payum/Payum/issues/627
=> Upgrade 3rd party libs requirments

docs/sofort/disable-notifications.md, src/Payum/Sofort/Action/StatusAction.php, src/Payum/Sofort/Tests/Action/StatusActionTest.php
=> [Sofort] Fix status action and cover with tests, make docs correction

CHANGELOG.md, src/Payum/Core/PayumBuilder.php
as discussed here: https://github.com/Payum/Payum/pull/679
=> integrate omnipay-v3-bridge

docs/payum-vs-omnipay.md
Fix broken links to omnipay gateways and spelling of GatewayInterface
=> Fix broken links to omnipay gateways

docs/symfony/get-it-started.md
Open question (please answer, if you can):
* "and delegate the job to capture action": Where is this action? And which "job" do you mean? The request?
=> Some docs improvements

composer.json
See https://github.com/Payum/Payum/issues/696  
Please double-check; I've never done this before. I removed the entire `suggests` key.
=> Remove `suggests`

docs/symfony/custom-payment-page.md
Custom payment page using Symfony and some custom data - "how to"
=> + custom payment page how-to for symfony

docs/supported-gateways.md
=> Change community gateway for Braintree

src/Payum/Be2Bill/Action/CaptureAction.php, src/Payum/Be2Bill/Action/StatusAction.php, src/Payum/Be2Bill/Tests/Action/CaptureActionTest.php, src/Payum/Be2Bill/Tests/Action/StatusActionTest.php
reworked version of https://github.com/Payum/Payum/pull/625 fixes https://github.com/Payum/Payum/issues/624
I was not able to test the solution because of Be2Bill API timeouts.
=> [be2bill] Add support of 3dSecure

src/Payum/Core/Bridge/PlainPhp/Security/HttpRequestVerifier.php, src/Payum/Core/Bridge/Symfony/Security/HttpRequestVerifier.php, src/Payum/Core/Security/Util/RequestTokenVerifier.php, src/Payum/Core/Tests/Bridge/PlainPhp/Security/HttpRequestVerifierTest.php, src/Payum/Core/Tests/Bridge/Symfony/Security/HttpRequestVerifierTest.php
This PR allows to process encoded urls, see #728.
=> use rawurldecode in HttpRequestVerifier

composer.json
=> adds conflict with league/uri-components: <1.7.1

docs/supported-gateways.md
Would be greate if you could add the gateway for PAYONE to the list of supported gateways.
=> add community gateway for PAYONE to docs

src/Payum/Klarna/Checkout/Action/Api/BaseApiAwareAction.php, src/Payum/Klarna/Checkout/Action/AuthorizeRecurringAction.php, src/Payum/Klarna/Invoice/Action/Api/BaseApiAwareAction.php, src/Payum/Stripe/Action/Api/CreateChargeAction.php, src/Payum/Stripe/Action/Api/CreateCustomerAction.php, src/Payum/Stripe/Action/Api/CreatePlanAction.php, src/Payum/Stripe/Action/Api/CreateSubscriptionAction.php, src/Payum/Stripe/Action/Api/CreateTokenAction.php, src/Payum/Stripe/Action/Api/ObtainTokenAction.php, src/Payum/Stripe/Action/Api/ObtainTokenForCreditCardAction.php
=> Fix deprecation comments, use proper phpdoc #771

composer.json, src/Payum/AuthorizeNet/Aim/composer.json, src/Payum/Be2Bill/composer.json, src/Payum/Core/composer.json, src/Payum/Klarna/Checkout/composer.json, src/Payum/Klarna/Invoice/composer.json, src/Payum/Offline/composer.json, src/Payum/Payex/composer.json, src/Payum/Paypal/ExpressCheckout/Nvp/composer.json, src/Payum/Paypal/Ipn/composer.json, src/Payum/Paypal/Masspay/Nvp/composer.json, src/Payum/Paypal/ProCheckout/Nvp/composer.json, src/Payum/Paypal/ProHosted/Nvp/composer.json, src/Payum/Paypal/Rest/composer.json, src/Payum/Skeleton/composer.json, src/Payum/Sofort/composer.json, src/Payum/Stripe/composer.json
This replaces #867 with the change made in all the packages
=> Update version alias to 1.6-dev

docs/supported-gateways.md
This gateway add ability to pay in bitcoin through payum, based on [tinkl.it](https://tinkl.it/) API
Update supported-gateways.md
=> Add new gateway Tinkl

src/Payum/Core/composer.json
This is one that I missed in #873
=> Fix PHP requirements for Payum/Core

src/Payum/Core/Security/Util/Random.php
For PHP 5 support, see: https://github.com/paragonie/random_compat
=> Use the CSPRNG provided by PHP 7

src/Payum/Core/Bridge/PlainPhp/Security/TokenFactory.php, src/Payum/Core/Tests/Bridge/PlainPhp/Security/TokenFactoryTest.php
Fixes #600
This is a continuation from #843
=> Replace basename for target url

src/Payum/Paypal/Rest/Action/CaptureAction.php, src/Payum/Paypal/Rest/Action/ConvertAction.php, src/Payum/Paypal/Rest/Action/StatusAction.php, src/Payum/Paypal/Rest/PaypalRestGatewayFactory.php, src/Payum/Paypal/Rest/Tests/Action/CaptureActionTest.php, src/Payum/Paypal/Rest/Tests/Action/ConvertActionTest.php, src/Payum/Paypal/Rest/Tests/Action/StatusActionTest.php
=> Handle Paypal Rest gateway when using standard Payment object

.github/workflows/subtree-split.yaml
Split sub-packages automatically with any changes to the main branch
=> Add subtree split workflow

docs/paypal/rest/get-it-started.md, src/Payum/Paypal/Rest/Action/CaptureAction.php, src/Payum/Paypal/Rest/Action/StatusAction.php, src/Payum/Paypal/Rest/Tests/Action/StatusActionTest.php
=> Handle cancel from PayPal rest action

src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/RefundTransactionAction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Api.php, src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php, src/Payum/Paypal/ExpressCheckout/Nvp/Request/Api/RefundTransaction.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/Api/RefundTransactionActionTest.php, src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Request/Api/RefundTransactionTest.php
RefundAction for Paypal Express Checkout
Fixes https://github.com/Payum/Payum/issues/754
=> Add PaypalExpressCheckout refund

src/Payum/Payex/Api/AgreementApi.php, src/Payum/Payex/Api/OrderApi.php, src/Payum/Payex/Api/RecurringApi.php
Ref http://www.payexpim.com/quick-guide/introduction/.
=> Updated Payex test url

src/Payum/Core/CoreGatewayFactory.php
=> Add support for Guzzle 7

src/Payum/Core/CoreGatewayFactory.php
=> Add support for Symfony HttpClient

src/Payum/Paypal/Rest/Action/SyncAction.php
=> Set authorization api in SyncAction

composer.json
Add roave/security-advisories as a dev dependency.
Replaces #798
Fixes #797
=> Add roave/security-advisories

src/Payum/Stripe/Action/Api/CreateChargeAction.php, src/Payum/Stripe/Action/Api/CreateCustomerAction.php, src/Payum/Stripe/Action/Api/CreatePlanAction.php, src/Payum/Stripe/Action/Api/CreateSubscriptionAction.php, src/Payum/Stripe/Action/Api/CreateTokenAction.php, src/Payum/Stripe/Constants.php
- Set constants for Payum Stripe name, url and version
- Set `setAppInfo` before every Stripe API request
Please feel free to recommend edits/changes to this PR, happy to adjust as needed!
=> Added setAppInfo details to Stripe API requests

src/Payum/Core/composer.json
Additional to https://github.com/Payum/Payum/pull/926
https://github.com/Payum/PayumBundle/pull/541/#issuecomment-1059960433
I am not sure how to poperly test this.
Tests are broken if try to install payum/core (this has nothing todo with my changes).
=> feat: move psr/log to composer require section and add v2 and v3

src/Payum/Be2Bill/Tests/Be2BillOffsiteGatewayFactoryTest.php
=> fix: psr-4 warning for Be2BillOffsiteGatewayFactoryTest #935

CHANGELOG.md, UPGRADE.md, composer.json, docs/iso4217-or-currency-details.md, docs/symfony/iso4217-or-currency-details.md, src/Payum/Core/Action/GetCurrencyAction.php, src/Payum/Core/CoreGatewayFactory.php, src/Payum/Core/Tests/Action/GetCurrencyActionTest.php, src/Payum/Core/composer.json
Remove deprecaqted payum/iso4217 package
=> Remove payum/iso4217

docs/get-it-started.md
Added Support for HttpPostRedirect in get-it-started documentation.
=> Added Support for HttpPostRedirect in doc

docs/laravel/get-it-started.md
to make the controller work in version 8, you have to put the namespace to the path of the controller
=> Update get-it-started.md (forgot about namespace)

docs/symfony/container-tags.md
Fixed multi begging typo to beginning
=> Fix documentation typo

src/Payum/Core/Request/GetHttpRequest.php
This PR allow to create dynamic properties for `GetHttpRequest.php` without changing the class content.
See related PR comments for more details : [#947](https://github.com/Payum/Payum/pull/947#issuecomment-2338633973)
=> Dynamic property for `payum/payum@^1.*` 
