Payum/Payum

src/Payum/Paypal/ProCheckout/Nvp/Resources/docs/get-it-started.md

In http://payum.org/doc/0.14/PaypalProCheckoutNvp/get-it-started the description links to the right paypal page, but the linked name is still paypal express, it should be pay pal pro checkout.

Fix error in payment name

---

src/Payum/AuthorizeNet/Aim/Action/FillOrderDetailsAction.php
src/Payum/AuthorizeNet/Aim/Tests/Action/FillOrderDetailsActionTest.php

Hi guys,
Not sure whether Authorize.NET updated their SDK but this PR fixes some fields name in the order details as per this definition (line 80): https://github.com/AuthorizeNet/sdk-php/blob/master/lib/AuthorizeNetAIM.php
Currently, the invoice number, email and customer ID are not populated or causing an error if these fields are set as required.

[Authorize.NET] Update order fields name.

---

src/Payum/Core/Request/GetHumanStatus.php

It work as is because the binary OR between to identical strings returns this string but it's clearly not the best way to compare string. Most probably a copy/paste error with GetBinaryStatus :)

Fix GetHumanStatus implementation

---

src/Payum/Core/Bridge/Buzz/ClientFactory.php

According to this issues:
https://github.com/Payum/Payum/issues/250
https://github.com/Payum/PayumBundle/issues/294
I know that in the current master branch Buzz replaced by the Guzzle PSR-7, but a lot of projects uses stable branch. Could you fix this issue in the current stable version?

Do not use the Cipher List for NSS

---

src/Payum/Core/Resources/docs/examples/1-paypal-create-gateway.md
src/Payum/Core/Resources/docs/examples/2-paypal-capture.md
src/Payum/Core/Resources/docs/examples/3-paypal-redirects.md
src/Payum/Core/Resources/docs/examples/4-get-status.md
src/Payum/Core/Resources/docs/examples/5-stripe-js-create-gateway.md
src/Payum/Core/Resources/docs/examples/6-stripe-js-capture.md
src/Payum/Core/Resources/docs/examples/7-stripe-js-render-form.md
src/Payum/Core/Resources/docs/examples/8-stripe-credit-card.md

Fixed broken link, as now it follows to 404 page.

Fixed "Back to examples" link

---

src/Payum/Core/Model/PaymentInterface.php
src/Payum/Core/Security/TokenInterface.php

According the [docs](https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html) method definition should contain brackets. Omitting those breaks any test suite which depends on Prophecy, when trying to double class, inherited from interface with magic method.
Example can be found [here](https://gist.github.com/ZloeSabo/5c9233753d0c8c493c90)

Fixes incomplete annotations of magic methods

---

src/Payum/Stripe/Action/Api/CreateCustomerAction.php
src/Payum/Stripe/Action/Api/CreatePlanAction.php
src/Payum/Stripe/Extension/CreateCustomerExtension.php
src/Payum/Stripe/Request/Api/CreatePlan.php
src/Payum/Stripe/Resources/docs/store-card-and-use-later.md
src/Payum/Stripe/Resources/docs/subscription-billing.md
src/Payum/Stripe/StripeCheckoutGatewayFactory.php
src/Payum/Stripe/Tests/Action/Api/CreatePlanActionTest.php
src/Payum/Stripe/Tests/Extension/CreateCustomerExtensionTest.php
src/Payum/Stripe/Tests/Request/Api/CreateChargeTest.php
src/Payum/Stripe/Tests/Request/Api/CreateCustomerTest.php
src/Payum/Stripe/Tests/Request/Api/CreatePlanTest.php

In this chapter we show how to create subscription plan and use it in future to charge a customer.
```php
<?php
// prepare.php
use Payum\Stripe\Request\Api\CreatePlan;
$plan = new \ArrayObject([
"amount" => 2000,
"interval" => "month",
"name" => "Amazing Gold Plan",
"currency" => "usd",
"id" => "gold"
]);
$payum->getGateway('gatewayName')->execute(new CreatePlan($plan));
```
This is a usual charge as we showed it in [get-it-started](get-it-started.md) with only these additions:
```php
<?php
// prepare.php
/** @var \Payum\Core\Model\PaymentInterface $payment */
$payment->setDetails([
'amount' => 2000,
'currency' => 'USD',
// everything in this section is never sent to the payment gateway
'local' => [
'save_card' => true,
'customer' => ['plan' => $plan['id']],
],
]);
```
* …

[stripe] Subscription billing.

---

composer.json
src/Payum/Core/Bridge/Symfony/Action/RenderTemplateAction.php
src/Payum/Core/Tests/Bridge/Symfony/Action/RenderTemplateActionTest.php

Payum currently has a hard dependency on Twig. Adding this Action allows using other template engines easily. In the PayumBundle we could add a service definition like this...
```yml
services:
payum.render_action:
class: Payum\Core\Bridge\Symfony\Action\RenderTemplateAction
arguments: ["@templating", '@PayumCore/layout.html.twig']
tags:
- { name: payum.action, all: true, alias: payum.action.render_template }
```
...and override the default twig render action.
This is backward compatible as long as twig is enabled in Symfony. And it also allows overriding the templates and using other template engines.

[Symfony Bridge] Action for Symfony Templating Component

---

composer.json
src/Payum/Be2Bill/Action/CaptureOffsiteNullAction.php
src/Payum/Core/Bridge/PlainPhp/Security/TokenFactory.php
src/Payum/Core/Security/AbstractTokenFactory.php
src/Payum/Core/Tests/Bridge/PlainPhp/Security/TokenFactoryTest.php
src/Payum/Core/Tests/Bridge/Symfony/Security/TokenFactoryTest.php
src/Payum/Core/Tests/Security/AbstractTokenFactoryTest.php
src/Payum/Paypal/ExpressCheckout/Nvp/Action/PurchaseAction.php

- Url null parameters  are used to be omitted now they are just empty
Url lib:    ['var1'=>null]  -->  http://example.com/  
Uri lib:    ['var1'=>null]  -->  http://example.com/?var1  
- Uri's are normalized out of the box. http://uri.thephpleague.com/uri/instantiation/
http://example.com:80/xxx   -->   http://example.com/xxx

Replace deprecated League\Url with League\Uri

---

CHANGELOG.md
src/Payum/Core/Model/BankAccount.php
src/Payum/Core/Model/BankAccountInterface.php
src/Payum/Core/Model/Payment.php
src/Payum/Core/Model/PaymentInterface.php

To support Direct debit payment (https://en.wikipedia.org/wiki/Direct_debit) or Giropay (https://en.wikipedia.org/wiki/Giropay) with different payment providers it is very useful to have a common interface for the bank account.
The Paypal API has way more fields for the bank account (https://developer.paypal.com/docs/classic/api/adaptive-accounts/AddBankAccount_API_Operation/). But I think it makes no sense to add all those fields.
@makasim what are your thoughts about that?

[WIP] Add BankAccount

---

src/Payum/Core/Registry/DynamicRegistry.php
src/Payum/Core/Tests/Registry/DynamicRegistryTest.php

The expected behaviour of a registry is to keep state. Unless changed
from the outside. So we keep instances created earlier and return them
on request.
Fixes #529

Keep already created gateway instances

---

src/Payum/Stripe/Resources/views/Action/obtain_checkout_token.html.twig

The stripe modal doesn't auto-open on load for me, possibly due to ordering of the block output? 
Using $(document).ready fixes it for me at least, and probably others - I'm seeing the issue whilst using sylius/sylius-standard.

Fix stripe auto open

---

src/Payum/Core/ApiAwareTrait.php
src/Payum/Core/Tests/ApiAwareTraitTest.php

In some cases, one may want to define `$apiClass` as an interface, not the implementation. This helps building more generic and subsitutable components.
Fixes https://github.com/Payum/JMSPaymentBridge/pull/6

Made ApiAwareTrait interface tolerant

---

src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/DoVoidAction.php
src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php
src/Payum/Paypal/ExpressCheckout/Nvp/Action/PaymentDetailsStatusAction.php
src/Payum/Paypal/ExpressCheckout/Nvp/Api.php
src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php
src/Payum/Paypal/ExpressCheckout/Nvp/Request/Api/DoVoid.php
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/Api/DoVoidActionTest.php
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/CancelActionTest.php
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/PaymentDetailsStatusActionTest.php
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Request/Api/DoVoidTest.php

Resubmitting the changes mistakenly requested on the read-only [PaypalExpressCheckoutNvp](https://github.com/Payum/PaypalExpressCheckoutNvp/pull/44) subtree split.

Adds DoVoid PayPal express NVP method as the gateway's Cancel action.

---

src/Payum/Core/CoreGatewayFactory.php

See issue https://github.com/Payum/Payum/issues/591
Nothing was added to the UPGRADE.md because it was already there:
https://github.com/gpou/Payum/blob/master/UPGRADE.md#130
> [gateway-factory] Option 'guzzle.client' was removed.

Remove guzzle.client from the gateway factory config

---

src/Payum/Core/Resources/docs/storages.md

Doctrine storage example uses 'SimplifiedXmlDriver' and pointing to the wrong directory, which produces unexpected errors during database migration. Changing the path to '/Payum/Core/Bridge/Doctrine/Resources/mapping' fixes the problem.

Doctrine storage example invalid path

---

composer.json
src/Payum/Core/Bridge/Defuse/Security/DefuseCypher.php
src/Payum/Core/Model/GatewayConfig.php
src/Payum/Core/Security/CryptedInterface.php
src/Payum/Core/Security/CypherInterface.php
src/Payum/Core/Storage/CryptoStorageDecorator.php
src/Payum/Core/Tests/Bridge/Defuse/Security/DefuseCypherTest.php
src/Payum/Core/Tests/Model/GatewayConfigTest.php
src/Payum/Core/Tests/Storage/CryptoStorageDecoratorTest.php
src/Payum/Core/composer.json

This is an alternative approach to this PR https://github.com/Payum/Payum/pull/635
Here's some benefits with my approach:
* The algo is not limited to openssl. One can use another one by implementing Cypher interface.
* Rely on `defuse/php-encryption` library. 
* Not only gateway configs could be secured but payment data or any other model (model has to implement CryptedInterface)
* No need for doctrine listener and manipulations with change sets. 
* It would work with previously not encrypted data, it will be encrypted while using.

[security] Add ability to crypt data stored to database

---

src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/CancelRecurringPaymentsProfileAction.php
src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php
src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelRecurringPaymentsProfileAction.php
src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/CancelActionTest.php
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/CancelRecurringPaymentsProfileActionTest.php

Because of very wide scope of support method, this action was preventing execution of other actions that handle Cancel request like CancelRecurringPaymentsProfileAction
fix #660

Fix PayPal express checkout NVP Cancel action support scope

---

src/Payum/Core/PayumBuilder.php

The PayumBuilder will fatally error out if you have Omnipay installed without the OmnipayBridge package.  This adds a check to ensure the bridge is present as well.

Check that the gateway factory exists

---

src/Payum/Stripe/Resources/views/Action/obtain_checkout_token.html.twig

Let Stripe set the language automatically by passing `data-locale="auto"` to the script.
See https://stripe.com/blog/checkout-in-more-languages for details.

Checkout: Automatically choose language

---

docs/get-it-started.md

I noticed in documentation that in capture.php is missing initializate two variables which are used bellow.

Missing variables

---

src/Payum/Offline/Action/ConvertPayoutAction.php
src/Payum/Offline/Action/PayoutAction.php
src/Payum/Offline/Action/RefundAction.php
src/Payum/Offline/Action/StatusAction.php
src/Payum/Offline/Constants.php
src/Payum/Offline/OfflineGatewayFactory.php
src/Payum/Offline/Tests/Action/ConvertPayoutActionTest.php
src/Payum/Offline/Tests/Action/PayoutActionTest.php
src/Payum/Offline/Tests/Action/RefundActionTest.php
src/Payum/Offline/Tests/Action/StatusActionTest.php

Created as copy of other actions.
Related to #688.
I have no idea what is [FIELD_PAID](https://github.com/Payum/Payum/blob/master/src/Payum/Offline/Action/CaptureAction.php#L22) for. There is no way to change it's value. But I added it into Payout as  FIELD_PAYOUT anyway.
There is [STATUS_CANCELED](https://github.com/Payum/Payum/blob/master/src/Payum/Offline/Action/StatusAction.php#L46) but there is no way to change status to canceled. Should I add CancelAction too?

Added refund and payout actions to offline gateway

---

.travis.yml
composer.json
src/Payum/Be2Bill/Action/CaptureOffsiteNullAction.php
src/Payum/Core/Bridge/PlainPhp/Security/TokenFactory.php
src/Payum/Core/Security/AbstractTokenFactory.php
src/Payum/Paypal/ExpressCheckout/Nvp/Action/PurchaseAction.php
src/Payum/Paypal/ProHosted/Nvp/Action/CaptureAction.php

see https://github.com/Payum/PayumBundle/issues/446
This PR allows the usage of `league/uri` version 5. I also dropped the php 5.5 support as `league/uri` itself requires 7.0 at least.
Disclaimer: tests run fine, I did not check this in a real project though. :)

use league/uri 5

---

src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/TransactionSearchAction.php
src/Payum/Paypal/ExpressCheckout/Nvp/Api.php
src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php
src/Payum/Paypal/ExpressCheckout/Nvp/Request/Api/TransactionSearch.php
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/Api/TransactionSearchActionTest.php

we need to call this endpoint to know the payment status of a legacy recurring payment.
i've tried to use the `GetRecurringPaymentsProfileDetailsAction` action, but my recurring payment has been created from a legacy version of paypal.
here is the paypal documentation that explain how this endpoint work: https://developer.paypal.com/docs/classic/api/merchant/TransactionSearch_API_Operation_NVP/?mark=TransactionSearch

[Paypal Express Checkout nvp] Introduce the TransactionSearch paypal api endpoint

---

src/Payum/Paypal/ExpressCheckout/Nvp/Api.php

If you're calling the API on behalf of a third-party merchant, you must specify the email address on file with PayPal of the third-party merchant or the merchant's account ID (sometimes called Payer ID).
`SUBJECT=Authorizing-Merchant-Email Or Authorizing-Merchant-Account-ID`
https://developer.paypal.com/docs/classic/api/NVPAPIOverview/

Add support for Subject authorization

---

docs/symfony/configure-payment-in-backend.md

This PR actually improve documentation for Gateway configuration in backend with Symfony.
I had to setup gateways configuration in background with Symfony, but I thought it was only compatible with Sonata (with `sonata_admin: true`). 
I didn't know that we can use `config_storage` alone. :sweat_smile:
Because of that, I did some really dirty weird things to implement gateways dynamic 
configuration from database (a `kernel.controller` listener that register gateways by updating `gateways` private property from registry, with & tons of reflection :nauseated_face: )
Also, I added an example of how we can implement FormType for configuring gateways configs.
Thanks

doc(symfony): improve documentation for Gateway configuration in backend

---

docs/encrypt-gateway-configs-stored-in-database.md
docs/index.md
docs/symfony/encrypt-gateway-configs-stored-in-database.md

We already have a guide that explains how to configure gateway configs encryption in database, but not for Symfony.
With this new page, we describe: 
- how to generate and store the cypher key
- how to configure cypher in Payum
- how to make encrypt/decrypt works with form type (e.g. `PaypalGatewayConfigType`)
Link to the rendered document: https://github.com/Kocal/Payum/blob/feat/symfony-encrypted-config-gateways/docs/symfony/encrypt-gateway-configs-stored-in-database.md

doc(symfony): add guide to show how encrypt Gateway configurations in database

---

src/Payum/Sofort/Api.php

Since PHP 7.2 ```count()``` yields a warning on invalid countable types [warning on invalid countable types](https://www.php.net/manual/en/function.count.php#refsect1-function.count-changelog). Added an ```is_array``` check before calling count on $params.

Suppress warning on PHP ^7.2

---

.travis.yml
composer.json
src/Payum/Core/Security/AbstractTokenFactory.php
src/Payum/Core/Security/Util/RequestTokenVerifier.php
src/Payum/Core/composer.json
src/Payum/Paypal/ExpressCheckout/Nvp/Action/PurchaseAction.php
src/Payum/Paypal/ProHosted/Nvp/Action/CaptureAction.php

Upgrading league/uri to version 6 fixes some deprecations and is a step closer to PHP 8 compatibility (required for tests in #873 to pass).
This requires dropping support for PHP 7.1, which is EOL for a year now and isn't supported by league/uri 6.

Upgrade league/uri to version 6

---

src/Payum/Core/CoreGatewayFactory.php
src/Payum/Core/Tests/CoreGatewayFactoryTest.php

When you use a function name as config, currently the function is executed and results in an error since the parameters don't match. This PR prevents such scenarios by skipping the execution of such functions when building the gateway config.
Fixes #692

Don't execute global functions when used as gateway config

---

.travis.yml
docs/php7.md
docs/storages.md
src/Payum/Core/Bridge/Doctrine/Resources/mapping/Token.mongodb.xml
src/Payum/Core/Bridge/Doctrine/Types/ObjectType.php
src/Payum/Core/Tests/Functional/Bridge/Doctrine/BaseMongoTest.php
src/Payum/Core/composer.json

This replaces #853 (and includes the original commit).
Additional changes in this PR is to run the unit tests on Travis with Mongodb.

Upgrade Doctrine mongodb-odm to 2.0

---

.travis.yml
composer.json

Allow PHP 8 in composer, and run unit tests Travis against PHP 8.
~Edit: Seems there are some failures related to league/uri, will have a look at them and get the tests to pass~
Tests pass with no code changes necessary

Add support for PHP 8

---

.travis.yml
composer.json
src/Payum/Core/Action/GetCurrencyAction.php
src/Payum/Core/ISO4217/Currency.php
src/Payum/Core/Tests/Action/GetCurrencyActionTest.php
src/Payum/Core/Tests/ISO4217/CurrencyTest.php
src/Payum/Core/composer.json

This PR replaces the usage of the `payum/iso4217` fork with the original repo `alcohol/iso4217`, while still keeping the OOP functionality.
This means there is one less repo for the Payum team to maintain while getting an up to date version of ISO4217 currencies.
This also means the https://github.com/Payum/iso4217 repository can be deprecated

Deprecate usage of payum/iso4217 and use alcohol/iso4217

---

docs/paypal/rest/get-it-started.md

I've seen multiple examples where developers point to the skd_config.ini full path instead of its directory (me included). This should fix that misconception.
Rebased from #818

Added helpful comments to get-it-started.md

---

composer.json
src/Payum/Stripe/Action/Api/CreateChargeAction.php
src/Payum/Stripe/Action/Api/CreateCustomerAction.php
src/Payum/Stripe/Action/Api/CreatePlanAction.php
src/Payum/Stripe/Action/Api/CreateSubscriptionAction.php
src/Payum/Stripe/Action/Api/CreateTokenAction.php
src/Payum/Stripe/composer.json

More complete PR to address #824 
Breaks backwards compatibility with v6 and previous versions of Stripe

Upgrade to Stripe v7

---

src/Payum/Stripe/Extension/CreateCustomerExtension.php
src/Payum/Stripe/Tests/Extension/CreateCustomerExtensionTest.php

With Stripe, if "save_card" is requested but card is declined, CreateCustomer fails and both $model['card'] && $model['customer'] are unset. 
Fix => keep card unchanged if CreateCustomer fails and move forward

 [Stripe][FIX] LogicException when card is declined

---

composer.json
src/Payum/Core/Bridge/Doctrine/Resources/mapping/ArrayObject.orm.xml
src/Payum/Core/Bridge/Doctrine/Resources/mapping/GatewayConfig.orm.xml
src/Payum/Core/Bridge/Doctrine/Resources/mapping/Payment.orm.xml
src/Payum/Core/Bridge/Doctrine/Resources/mapping/Payout.orm.xml
src/Payum/Core/Tests/Functional/Bridge/Doctrine/BaseMongoTest.php

As pointed out by @Prometee in https://github.com/Payum/Payum/issues/922#issuecomment-984156298, switching `json_array` to `json` shouldn't be a BC break because we don't store `null` values in the DB.
Fixes #922

Add support for Doctrine DBAL 3

---

.github/workflows/ci.yaml
composer.json

So far, no errors has been picked up on PHP 8.1. So this PR only adds PHP 8.1 to GH actions, so that all tests runs against PHP 8.1.

Support PHP 8.1

---

src/Payum/Core/Bridge/Psr/Log/LogExecutedActionsExtension.php
src/Payum/Core/Bridge/Psr/Log/LoggerExtension.php
src/Payum/Core/Tests/Bridge/Psr/Log/LoggerExtensionTest.php
src/Payum/Core/Tests/Mocks/Action/LoggerAwareAction.php

Hi. This will fix this error i got with symfony 6 (and Upgrading psr/log (2.0.0 => 3.0.0))
`PHP Fatal error:  Declaration of Payum\Core\Bridge\Psr\Log\LoggerExtension::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in /vendor/payum/core/Payum/Core/Bridge/Psr/Log/LoggerExtension.php on line 34
`
There are probably more, but these are the first that i get.

feat: add return hint for setLogger() to void

---

src/Payum/Core/Bridge/Symfony/Form/Type/CreditCardExpirationDateType.php
src/Payum/Core/Bridge/Symfony/Form/Type/GatewayChoiceType.php
src/Payum/Core/Bridge/Symfony/Form/Type/GatewayFactoriesChoiceType.php

Solution with annotations.
Should be changed to Return values with next major version

feat: fix symfony6 deprecation messages for getParent()

---

composer.json
docs/frameworks-and-e-commerce-integration.md
docs/storages.md
docs/symfony/storages.md
src/Payum/Core/Bridge/Propel/Model/Payment.php
src/Payum/Core/Bridge/Propel/Model/Token.php
src/Payum/Core/Bridge/Propel/Storage/Propel1Storage.php
src/Payum/Core/Bridge/Propel2/Model/Payment.php
src/Payum/Core/Bridge/Propel2/Model/PaymentQuery.php
src/Payum/Core/Bridge/Propel2/Model/Token.php
src/Payum/Core/Bridge/Propel2/Model/TokenQuery.php
src/Payum/Core/Bridge/Propel2/Storage/Propel2Storage.php

Propel hasn't been updated for a long time, so I think we should drop support for it in V2.
See #938

Deprecate Propel storage

---

src/Payum/Core/Request/GetHttpRequest.php

Fixes 8.2 warning: "Creation of dynamic property Payum\Core\Request\GetHttpRequest::$headers is deprecated"

PHP 8.2: Creation of dynamic property is deprecated

---

composer.json
phpstan-baseline.neon
rector.php
src/Payum/Be2Bill/Action/CaptureAction.php
src/Payum/Be2Bill/Action/CaptureOffsiteAction.php
src/Payum/Be2Bill/Action/CaptureOffsiteNullAction.php
src/Payum/Be2Bill/Action/NotifyNullAction.php
src/Payum/Be2Bill/Api.php
src/Payum/Core/Bridge/Spl/ArrayObject.php
src/Payum/Core/Bridge/Symfony/Form/Type/GatewayConfigType.php
src/Payum/Core/Model/ArrayObject.php
src/Payum/Core/Reply/HttpPostRedirect.php
src/Payum/Core/Reply/HttpRedirect.php
src/Payum/Core/Security/Util/Mask.php
src/Payum/Core/Security/Util/Random.php
src/Payum/Core/Tests/Action/AuthorizePaymentActionTest.php
src/Payum/Core/Tests/Action/CapturePaymentActionTest.php
src/Payum/Core/Tests/Action/ExecuteSameRequestWithModelDetailsActionTest.php
src/Payum/Core/Tests/Action/PayoutPayoutActionTest.php
src/Payum/Core/Tests/Bridge/Spl/ArrayObjectTest.php
src/Payum/Core/Tests/Bridge/Symfony/Validator/Constraints/CreditCardDateValidatorTest.php
src/Payum/Core/Tests/Mocks/Document/ArrayObject.php
src/Payum/Core/Tests/Mocks/Entity/ArrayObject.php
src/Payum/Core/Tests/Mocks/Model/TestModel.php
src/Payum/Klarna/Invoice/Action/Api/BaseApiAwareAction.php
src/Payum/Klarna/Invoice/Action/Api/GetAddressesAction.php
src/Payum/Klarna/Invoice/Action/Api/PopulateKlarnaFromDetailsAction.php
src/Payum/Klarna/Invoice/Tests/Action/Api/PopulateKlarnaFromDetailsActionTest.php
src/Payum/Sofort/Action/StatusAction.php
src/Payum/Sofort/SofortGatewayFactory.php

```
Remaining self deprecation notices (97)
40x: Function utf8_decode() is deprecated
36x in PopulateKlarnaFromDetailsActionTest::testShouldPopulateKlarnaFromDetails from Payum\Klarna\Invoice\Tests\Action\Api
3x in PopulateKlarnaFromDetailsActionTest::testShouldCorrectlyPutPartialArticles from Payum\Klarna\Invoice\Tests\Action\Api
1x in PopulateKlarnaFromDetailsActionTest::testShouldNotFaileIfEmptyDetailsGiven from Payum\Klarna\Invoice\Tests\Action\Api
36x: Function utf8_encode() is deprecated
26x in GetAddressesActionTest::testShouldCallKlarnaGetAddresses from Payum\Klarna\Invoice\Tests\Action\Api
1x in ActivateActionTest::testShouldCatchKlarnaExceptionAndSetErrorInfoToDetails from Payum\Klarna\Invoice\Tests\Action\Api
1x in CancelReservationActionTest::testShouldCatchKlarnaExceptionAndSe …
```

Remove deprecation notices

---

src/Payum/AuthorizeNet/Aim/Tests/Action/ConvertPaymentActionTest.php
src/Payum/Klarna/Invoice/composer.json
src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/ConvertPaymentActionTest.php
src/Payum/Paypal/ProCheckout/Nvp/Tests/Action/ConvertPaymentActionTest.php
src/Payum/Paypal/ProHosted/Nvp/Tests/Action/ConvertPaymentActionTest.php
src/Payum/Paypal/Rest/Tests/PaypalRestGatewayFactoryTest.php

The `fp/klarna-invoice` package doesn't seem to be maintained anymore, and currently emits a lot of deprecation notices when using with PHP 8+
```
PHP Deprecated:  Return type of KlarnaConfig::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/fp/klarna-invoice/klarnaconfig.php on line 130
PHP Deprecated:  Return type of KlarnaConfig::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/fp/klarna-invoice/klarnaconfig.php on line 142
PHP Deprecated:  Return type of …
```

Update KlarnaInvoice package to use solidworx/klarna-invoice

---

docs/stripe/subscription-billing.md

I fix manual because it is obsolete and don't work. 
NOTE: Also I Create new Payum/Stripe Actions that used the new [Prices API](https://stripe.com/docs/api/plans/create#prices) , that replaces the Plans API and has more options. I can create another Pull Request for these actions in [payum/stripe](https://github.com/Payum/Stripe) repository if you want.

Fix Manual for Using Recurring Payments in Stripe.

---

composer.json
src/Payum/Paypal/Rest/Tests/PaypalRestGatewayFactoryTest.php

try to fix ci error on --prefer-lowest
One test is changed to fix this.
Additional the `"doctrine/annotations": "^1.14.3 || ^2.0.1", ` is now added.
I guess this dependency was made optional in some other dependency and was now missing.

feat: fix ci

---

.github/workflows/rector.yaml
composer.json
rector.php

fix `rector`-run for 1.7.x
PR to fix external Warnings
https://github.com/formapro/KlarnaInvoice/pull/3

feat: fix rector

---

.github/workflows/ci.yaml
.github/workflows/subtree-split.yaml

add testruns for PHP 8.3
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore: fix ci deprecations

---

UPGRADE.md
src/Payum/Core/ApiAwareInterface.php
src/Payum/Core/ApiAwareTrait.php
src/Payum/Core/CoreGatewayFactory.php
src/Payum/Core/Gateway.php
src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/BaseApiAwareAction.php

Deprecate the `payum.api` config and setting APIs using the ApiAwareInterface and ApiAwareTrait.
Instead, the API can just be added to the action through the constructor. This helps with static-analysis, since we can set the correct property and type for the API. It also allows multiple API classes to be added to an action.
E.G To move away from the `payum.api` config in Stripe, the following changes can be made in the gateway factory:
```php
$config->validateNotEmpty(['publishable_key', 'secret_key']);
$api = new Keys($config['publishable_key'], $config['secret_key']);
$config->defaults([
// ...
'payum.action.create_charge' => new CreateChargeAction($api),
]);
/****/
class CreateChargeAction {
protected $api;
public function __construct(Keys $api)
{
$this->api = $api;
}
}
```

Deprecate setting APIs on actions through ApiAwareInterface and ApiAwareTrait

---

docs/authorize-net/aim/get-it-started.md
docs/be2bill/direct.md
docs/be2bill/offsite.md
docs/encrypt-gateway-configs-stored-in-database.md
docs/get-it-started.md
docs/klarna/checkout/get-it-started.md
docs/klarna/invoice/get-it-started.md
docs/laravel/blade-templating.md
docs/offline/get-it-started.md
docs/payex/get-it-started.md
docs/paypal/express-checkout/get-it-started.md
docs/paypal/masspay/get-it-started.md
docs/paypal/pro-checkout/get-it-started.md
docs/paypal/pro-hosted/get-it-started.md
docs/paypal/rest/get-it-started.md
docs/sofort/get-it-started.md
docs/stripe/checkout.md
docs/stripe/direct.md
docs/stripe/js.md
src/Payum/Core/PayumBuilder.php
src/Payum/Core/Tests/PayumBuilderTest.php

Remove the need to call `addDefaultStorages()` on PayumBuilder. Register the storages by default if it's not set

Add default storages when not defined

---

composer.json
src/Payum/Core/Bridge/PlainPhp/Security/TokenFactory.php

According to the changelog none of the functions that got dropped in 7.0 version were used by payum/payum but some are seemingly missing from the changelog because the Path constructor being changed to private was not mentioned
https://github.com/thephpleague/uri/blob/master/CHANGELOG.md
https://github.com/thephpleague/uri-components/blob/master/CHANGELOG.md
If I were to make a similar pull request into 1.7.x would it be possible to accept it and make a new patch version or the fact it's a major version bump for a dependency would forbide that ?

Allow ^7.0 for league/uri and league/uri-components

---

src/Payum/Core/Bridge/Symfony/Action/GetHttpRequestAction.php
src/Payum/Core/Bridge/Symfony/Action/ObtainCreditCardAction.php
src/Payum/Core/Bridge/Symfony/Action/RenderTemplateAction.php
src/Payum/Core/Bridge/Symfony/Builder/CoreGatewayFactoryBuilder.php
src/Payum/Core/Bridge/Symfony/Builder/GatewayFactoryBuilder.php
src/Payum/Core/Bridge/Symfony/Builder/HttpRequestVerifierBuilder.php
src/Payum/Core/Bridge/Symfony/Builder/ObtainCreditCardActionBuilder.php
src/Payum/Core/Bridge/Symfony/Builder/TokenFactoryBuilder.php
src/Payum/Core/Bridge/Symfony/ContainerAwareCoreGatewayFactory.php
src/Payum/Core/Bridge/Symfony/ContainerAwareRegistry.php
src/Payum/Core/Bridge/Symfony/Event/ExecuteEvent.php
src/Payum/Core/Bridge/Symfony/Extension/EventDispatcherExtension.php
src/Payum/Core/Bridge/Symfony/Form/Type/CreditCardExpirationDateType.php
src/Payum/Core/Bridge/Symfony/Form/Type/CreditCardType.php
src/Payum/Core/Bridge/Symfony/Form/Type/GatewayChoiceType.php
src/Payum/Core/Bridge/Symfony/Form/Type/GatewayConfigType.php
src/Payum/Core/Bridge/Symfony/Form/Type/GatewayFactoriesChoiceType.php
src/Payum/Core/Bridge/Symfony/PayumEvents.php
src/Payum/Core/Bridge/Symfony/Reply/HttpResponse.php
src/Payum/Core/Bridge/Symfony/ReplyToSymfonyResponseConverter.php
src/Payum/Core/Bridge/Symfony/Security/HttpRequestVerifier.php
src/Payum/Core/Bridge/Symfony/Security/TokenFactory.php
src/Payum/Core/Bridge/Symfony/Validator/Constraints/CreditCardDate.php
src/Payum/Core/Bridge/Symfony/Validator/Constraints/CreditCardDateValidator.php

Deprecate the Symfony Bridge classes, in favour of a full integration in PayumBundle.
These classes will be moved to PayumBundle, so that the bundle is fully responsible for it's own integration and the integration is not split between repositories. 
Fixes #838
Related: Payum/PayumBundle#557

Deprecate the Symfony bridge in favour of using PayumBundle

---

src/Payum/Core/Model/Payment.php

Implicitly marking parameter $creditCard as nullable is deprecated, the explicit nullable type must be used instead in vendor/payum/payum/src/Payum/Core/Model/Payment.php line 185

Update Payment.php - PHP7.4 warning
